apiVersion: v2
name: stardog
description: Helm chart to deploy Stardog Cluster and associated services
version: 2.1.0
appVersion: latest
home: https://stardog-union.github.io/helm-charts-sa/
icon: https://s3.amazonaws.com/stardog-logos.public/stardog-logo.png
maintainers:
  - name: Stardog Union
    email: tech@stardog.com
    url: https://www.stardog.com
dependencies:
  - name: zookeeper
    version: 11.3.1
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: zookeeper.enabled
